# Generated by Django 5.0.4 on 2024-05-01 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='firts_name',
            new_name='first_name',
        ),
    ]
